# Configuration SonarQube pour analyse locale
# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/

sonar.projectKey=retronova-industry_Retronova-api
sonar.organization=retronova-industry

sonar.python.coverage.reportPaths=coverage.xml